services:
    rss_cleaner.entry.repository:
        class: RssCleanerBundle\Repository\FreshRssEntryRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - RssCleanerBundle\Entity\FreshRssEntry
    rss_cleaner.expression.repository:
        class: RssCleanerBundle\Repository\ExpressionRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - RssCleanerBundle\Entity\Expression
