show_notes_to_zoid_details:
    path:     /notes/detail/{noteId}
    defaults: { _controller: ShowNotesToZoidBundle:Default:detail }
    requirements:
        noteId: "[a-z0-9-]+"

show_notes_to_zoid_test:
    path:     /notes/test
    defaults: { _controller: ShowNotesToZoidBundle:Default:test }
show_notes_to_zoid_homepage:
    path:     /devnotes/{categoryId}
    defaults: { _controller: ShowNotesToZoidBundle:Default:index, categoryId: '' }
    requirements:
        categoryId: "[a-z0-9-]{0,}"
