<?php

namespace RssCleanerBundle\Repository;

/**
 * FreshRssEntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FreshRssEntryRepository extends \Doctrine\ORM\EntityRepository
{
}
