services:
  twitter.service.api:
    class: AppBundle\Service\Twitter\Api
    arguments:
      - @twitter.vendor.api
      - @logger
    tags:
      - {name: monolog, channel: twitter}
  twitter.service.timeline:
    class: AppBundle\Service\Twitter\Timeline
    arguments:
      - @twitter.service.api
  twitter.vendor.api:
    class: TwitterAPIExchange
    arguments: [%twitter%]