services:
  twitter.service.api:
    class: AppBundle\Service\Twitter\Api
    arguments:
      - "%twitter%"
  twitter.service.timeline:
    class: AppBundle\Service\Twitter\Timeline
    arguments:
      - @twitter.service.api