services:
  commcenter.service.twitter.api:
    class: AppBundle\Service\Twitter\Api
    arguments:
      - @vendor.twitter.api
      - @logger
    tags:
      - {name: monolog, channel: twitter}
  commcenter.service.twitter.timeline:
    class: AppBundle\Service\Twitter\Timeline
    arguments:
      - @commcenter.service.twitter.api
      - @commcenter.repository.twitter
  commcenter.repository.twitter:
    class: AppBundle\Repository\TwitterRepository
    factory: ["@doctrine_mongodb", getRepository]
    arguments:
      - AppBundle\Document\TwitterEntry
  vendor.twitter.api:
    class: TwitterAPIExchange
    arguments: [%twitter%]
  commcenter.twig_extension.kint_dump:
    class: AppBundle\Twig\TwigKintDumpExtension
    public: false
    arguments:
      - %kernel.environment%
    tags:
       - { name: twig.extension }
  commcenter.twig_extension.build_twitter_url:
    class: AppBundle\Twig\TwigTwitterUrlExtension
    public: false
    tags:
       - { name: twig.extension }